package com.example.mapasssist

import android.app.AlertDialog
import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.graphics.*
import android.net.Uri
import android.provider.MediaStore
import androidx.core.content.FileProvider
import com.example.mapasssist.data.DncEntryCodec
import com.example.mapasssist.data.TextFile
import java.io.File
import java.io.FileOutputStream

object DncImageExporter {
    fun share(context: Context, file: TextFile) { val uri = cacheImage(context, file); context.startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).apply { type = "image/png"; putExtra(Intent.EXTRA_STREAM, uri); addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION) }, "Share DNC card")) }
    fun download(context: Context, file: TextFile) { val name = safeName(file) + ".png"; val existing = context.contentResolver.query(MediaStore.Downloads.EXTERNAL_CONTENT_URI, arrayOf(MediaStore.MediaColumns._ID), "${MediaStore.MediaColumns.DISPLAY_NAME}=? AND ${MediaStore.MediaColumns.RELATIVE_PATH}=?", arrayOf(name, "Download/Map Assist/"), null)?.use { it.moveToFirst() } == true; if (existing) AlertDialog.Builder(context).setTitle("Replace existing image?").setMessage("$name already exists in Downloads/Map Assist. Replacing it cannot be undone.").setNegativeButton("Cancel", null).setPositiveButton("Replace") { _, _ -> saveDownload(context, file, name, true) }.show() else saveDownload(context, file, name, false) }
    private fun saveDownload(context: Context, file: TextFile, name: String, replace: Boolean) { if (replace) context.contentResolver.delete(MediaStore.Downloads.EXTERNAL_CONTENT_URI, "${MediaStore.MediaColumns.DISPLAY_NAME}=? AND ${MediaStore.MediaColumns.RELATIVE_PATH}=?", arrayOf(name, "Download/Map Assist/")); val values = ContentValues().apply { put(MediaStore.MediaColumns.DISPLAY_NAME, name); put(MediaStore.MediaColumns.MIME_TYPE, "image/png"); put(MediaStore.MediaColumns.RELATIVE_PATH, "Download/Map Assist/") }; val uri = context.contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values) ?: return; context.contentResolver.openOutputStream(uri)?.use { render(file).compress(Bitmap.CompressFormat.PNG, 100, it) }; android.widget.Toast.makeText(context, "Saved to Downloads/Map Assist", android.widget.Toast.LENGTH_LONG).show() }
    private fun cacheImage(context: Context, file: TextFile): Uri { val dir = File(context.cacheDir,"images").apply { mkdirs() }; val out = File(dir,"dnc_${file.id}.png"); FileOutputStream(out).use { render(file).compress(Bitmap.CompressFormat.PNG,100,it) }; return FileProvider.getUriForFile(context,"${context.packageName}.fileprovider",out) }
    private fun render(file: TextFile): Bitmap { val rows = DncEntryCodec.decode(file.entriesJson); val width = 900; val dateX=48f; val addressX=130f; val infoX=575f; val rowHeights=rows.map { maxOf(68, 36 + maxOf((it.address.length+38)/42, (it.supportingInformation.length+23)/24)*28) }; val height = maxOf(390, 260 + rowHeights.sum() + 82); val bitmap = Bitmap.createBitmap(width,height,Bitmap.Config.ARGB_8888); val canvas=Canvas(bitmap); canvas.drawColor(Color.rgb(248,244,234)); val p=Paint(Paint.ANTI_ALIAS_FLAG); p.color=Color.rgb(181,151,104); p.style=Paint.Style.STROKE; p.strokeWidth=12f; canvas.drawRect(18f,18f,(width-18).toFloat(),(height-18).toFloat(),p); p.style=Paint.Style.FILL;p.color=Color.rgb(23,33,29);p.textSize=42f;canvas.drawText("${file.mapNo} - ${file.title}",48f,82f,p);p.textSize=20f; canvas.drawText("DATE",dateX,132f,p);canvas.drawText("ADDRESS",addressX,132f,p);canvas.drawText("SUPPORTING",infoX,122f,p);canvas.drawText("INFORMATION",infoX,145f,p); var y=160f; rows.forEachIndexed { i,row -> val h=rowHeights[i].toFloat(); p.color=if(i%2==0) Color.rgb(238,231,214) else Color.rgb(248,244,234);canvas.drawRect(36f,y,(width-36).toFloat(),y+h,p);p.color=Color.rgb(23,33,29);p.textSize=22f;canvas.drawText(row.date,dateX,y+29,p); drawWrap(canvas,p,row.address,addressX,y+28,425f,27f); drawWrap(canvas,p,row.supportingInformation,infoX,y+28,275f,27f);y+=h }; p.color=Color.rgb(190,184,171);p.strokeWidth=2f;canvas.drawLine(116f,108f,116f,y,p);canvas.drawLine(558f,108f,558f,y,p); p.textSize=18f;p.color=Color.rgb(89,97,93);p.textAlign=Paint.Align.CENTER;canvas.drawText("Please draw new entries to the attention of the Territory Servant.",width/2f,(height-50).toFloat(),p);return bitmap }
    private fun drawWrap(canvas: Canvas,p: Paint,text:String,x:Float,y:Float,width:Float,line:Float) { var lineText="";var yy=y;text.split(" ").forEach { word -> val test=if(lineText.isBlank()) word else "$lineText $word";if(p.measureText(test)>width){canvas.drawText(lineText,x,yy,p);yy+=line;lineText=word}else lineText=test };if(lineText.isNotBlank())canvas.drawText(lineText,x,yy,p) }
    private fun safeName(file: TextFile) = ("${file.mapNo}_${file.title}").replace(Regex("[^A-Za-z0-9_-]"), "_")
}
